# **Step 1: Import the necessary libraries**

In [1]:
import pandas as pd
import scipy
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns
import matplotlib.pyplot as plt

# **Step 2: Data Importing**

In [2]:
df = pd.read_csv('SampleData.csv')

# **Step 3 : Seggregation of dataset into Matrix of Features & Dependent Variable Vector**

In [3]:
x_features = df.iloc[:, :-1].values
y_dependent = df.iloc[:, -1].values

In [4]:
print(x_features)

[['USA' 34.0 70000.0]
 ['Spain' 28.0 55000.0]
 ['Germany' 31.0 60000.0]
 ['USA' 39.0 nan]
 ['Germany' 41.0 72000.0]
 ['USA' 36.0 65000.0]
 ['Spain' nan 59000.0]
 ['USA' 49.0 85000.0]
 ['Germany' 51.0 90000.0]
 ['USA' 38.0 71000.0]]


In [5]:
print(y_dependent)

['No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes']


# **Step 4 : Handling missing Data**

In [6]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x_features[:,1:3])
x_features[:,1:3] = imputer.transform(x_features[:,1:3])

In [8]:
print (x_features)

[['USA' 34.0 70000.0]
 ['Spain' 28.0 55000.0]
 ['Germany' 31.0 60000.0]
 ['USA' 39.0 69666.66666666667]
 ['Germany' 41.0 72000.0]
 ['USA' 36.0 65000.0]
 ['Spain' 38.55555555555556 59000.0]
 ['USA' 49.0 85000.0]
 ['Germany' 51.0 90000.0]
 ['USA' 38.0 71000.0]]


# **Step 5 : Encoding Categorical Data : One Hot Encoding**

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
column_transformer = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x_features = np.array(column_transformer.fit_transform(x_features))

In [10]:
print(x_features)

[[0.0 0.0 1.0 34.0 70000.0]
 [0.0 1.0 0.0 28.0 55000.0]
 [1.0 0.0 0.0 31.0 60000.0]
 [0.0 0.0 1.0 39.0 69666.66666666667]
 [1.0 0.0 0.0 41.0 72000.0]
 [0.0 0.0 1.0 36.0 65000.0]
 [0.0 1.0 0.0 38.55555555555556 59000.0]
 [0.0 0.0 1.0 49.0 85000.0]
 [1.0 0.0 0.0 51.0 90000.0]
 [0.0 0.0 1.0 38.0 71000.0]]


# **Step 6 : Encoding Categorical Data : Label Encoding**

In [11]:
from sklearn.preprocessing import LabelEncoder
label_encoding = LabelEncoder()
y_dependent = label_encoding.fit_transform(y_dependent)

In [12]:
print(y_dependent)

[0 1 0 1 0 1 0 1 0 1]


# **Step 7 : Splitting dataset into Training and Test Dataset**

In [14]:
from sklearn.model_selection import train_test_split
x_train_set, x_test_set, y_train_set, y_test_set = train_test_split(x_features, y_dependent, test_size = 0.2, random_state = 1)

In [15]:
print(x_train_set)

[[0.0 1.0 0.0 38.55555555555556 59000.0]
 [1.0 0.0 0.0 41.0 72000.0]
 [0.0 0.0 1.0 34.0 70000.0]
 [0.0 0.0 1.0 39.0 69666.66666666667]
 [0.0 1.0 0.0 28.0 55000.0]
 [0.0 0.0 1.0 49.0 85000.0]
 [1.0 0.0 0.0 51.0 90000.0]
 [0.0 0.0 1.0 36.0 65000.0]]


In [16]:
print(x_test_set)

[[1.0 0.0 0.0 31.0 60000.0]
 [0.0 0.0 1.0 38.0 71000.0]]


In [17]:
print(y_train_set)

[0 0 0 1 1 1 0 1]


In [18]:
print(y_test_set)

[0 1]
